import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

/**
 * MongoDB document representing a biometric credential.
 *
 * Stores the public key generated by the device's secure hardware.
 * Each user can have multiple credentials (one per device).
 */
@Schema({ timestamps: true })
export class BiometricCredential extends Document {
  @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true })
  userId: Types.ObjectId;

  @Prop({ required: true })
  publicKey: string;

  @Prop()
  keyAlias: string;

  @Prop({ default: true })
  isActive: boolean;
}

export type BiometricCredentialDocument = BiometricCredential & Document;
export const BiometricCredentialSchema =
  SchemaFactory.createForClass(BiometricCredential);

// Compound index: one active credential per user per keyAlias
BiometricCredentialSchema.index(
  { userId: 1, keyAlias: 1 },
  { unique: true, sparse: true },
);
